networks:
  nezha:
    name: nezha
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.2.0/24

services:
  panel:
    image: ghcr.io/nezhahq/nezha:latest
    container_name: nezha-panel
    restart: always
    environment:
      - TZ=Asia/Shanghai
    networks:
      nezha:
        ipv4_address: 172.30.2.10
    volumes:
      - ${PWD}/nezha:/dashboard/data

  nginx:
    image: nginx:stable-alpine
    container_name: nezha-nginx
    restart: always
    depends_on:
      - panel
    environment:
      - TZ=Asia/Shanghai
    networks:
      nezha:
        ipv4_address: 172.30.2.20
    ports:
      - '55080:80/tcp'
    volumes:
      - ${PWD}/nginx:/etc/nginx/conf.d

  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: nezha-tunnel
    restart: always
    depends_on:
      - panel
    environment:
      - TZ=Asia/Shanghai
    network_mode: bridge
    dns:
      - 10.10.10.2
    command: tunnel --protocol http2 run --token ${TUNNEL_TOKEN}

  watch:
    image: containrrr/watchtower:latest
    container_name: nezha-watch
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 0 6 * * *
      # - WATCHTOWER_INTERVAL=3600
    network_mode: bridge
    dns:
      - 10.10.10.2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      disable: true
